#!/bin/bash

if [ "$#" -lt "1" ]; then
	echo "usage: $0 <class name>"
	exit 1
fi

# find java claspath
DIR=`dirname $0`
#echo "we are operating from: $DIR"
CLASSPATH=:$DIR/../util/build/lib-run/*
CLASSPATH+=:$DIR/../bin/
CLASSPATH+=.
#echo "CLASSPATH=$CLASSPATH"

CMD="java -cp $CLASSPATH"
exec $CMD "$@"
